site_name: Ateliers ib Cegos
site_url: https://ib-cegos.github.io/labs

theme:
  name: material
  language: fr

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/css/main.css

extra_javascript:
  - assets/js/main.js

nav:
  - Accueil: index.md
  - msms030: msms030/README.md
  - ms503: ms503/README.md