site_name: Ateliers ib Cegos
site_url: https://ib-cegos.github.io/labs
copyright: ib Cegos

theme:
  name: mkdocs
  language: fr
  custom_dir: themes/original

hooks:
  - hooks/content_processor.py

plugins:
  - search
  - macros:
    modules:
      - tools
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      locale: fr
      exclude: 
        - "*/README.md"
        - index.md

markdown_extensions:
  - admonition
  - tables
  - toc
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
